annotations:
  artifacthub.io/repository: kubewarden-policy-library
  catalog.cattle.io/hidden: "true"
  catalog.cattle.io/type: kubewarden-policy
  catalog.cattle.io/ui-component: kubewarden
  kubewarden/displayName: Kyverno validator
  kubewarden/mutation: "false"
  kubewarden/registry: ghcr.io
  kubewarden/repository: kubewarden/policies/kyverno-validator
  kubewarden/resources: Pod
  kubewarden/rules: |
    - apiGroups:
      - ''
      apiVersions:
      - v1
      resources:
      - pods
      operations:
      - CREATE
      - UPDATE
  kubewarden/tag: v0.1.7
appVersion: 0.1.7
description: This is a POC
home: https://github.com/kubewarden/policies
keywords:
- psp
- container
- runtime
name: kyverno-validator
sources:
- ghcr.io/kubewarden/policies/kyverno-validator:v0.1.7
version: 0.1.7
