annotations:
  artifacthub.io/repository: kubewarden-policy-library
  catalog.cattle.io/hidden: "true"
  catalog.cattle.io/type: kubewarden-policy
  catalog.cattle.io/ui-component: kubewarden
  kubewarden/displayName: Seccomp PSP
  kubewarden/mutation: "false"
  kubewarden/registry: ghcr.io
  kubewarden/repository: kubewarden/policies/seccomp-psp
  kubewarden/resources: Pod
  kubewarden/rules: |
    - apiGroups:
      - ''
      apiVersions:
      - v1
      resources:
      - pods
      operations:
      - CREATE
      - UPDATE
  kubewarden/tag: v1.0.11
appVersion: 1.0.11
description: Pod Security Policy that controls usage of Seccomp profile
home: https://github.com/kubewarden/policies
keywords:
- psp
- seccomp
name: seccomp-psp
sources:
- ghcr.io/kubewarden/policies/seccomp-psp:v1.0.11
version: 1.0.11
