annotations:
  artifacthub.io/repository: kubewarden-policy-library
  catalog.cattle.io/hidden: "true"
  catalog.cattle.io/type: kubewarden-policy
  catalog.cattle.io/ui-component: kubewarden
  kubewarden/displayName: Allowed Proc Mount Types PSP
  kubewarden/mutation: "false"
  kubewarden/registry: ghcr.io
  kubewarden/repository: kubewarden/policies/allowed-proc-mount-types-psp
  kubewarden/resources: Pod
  kubewarden/rules: |
    - apiGroups:
      - ''
      apiVersions:
      - v1
      resources:
      - pods
      operations:
      - CREATE
      - UPDATE
  kubewarden/tag: v1.0.8
appVersion: 1.0.8
description: Replacement for the Kubernetes Pod Security Policy that controls the
  usage of /proc mount types
home: https://github.com/kubewarden/allowed-proc-mount-types-psp-policy
keywords:
- psp
- container
- runtime
name: allowed-proc-mount-types-psp
sources:
- ghcr.io/kubewarden/policies/allowed-proc-mount-types-psp:v1.0.8
version: 1.0.8
