annotations:
  artifacthub.io/repository: volumes-psp
  catalog.cattle.io/hidden: "true"
  catalog.cattle.io/type: kubewarden-policy
  catalog.cattle.io/ui-component: kubewarden
  kubewarden/displayName: Volumes PSP
  kubewarden/mutation: "false"
  kubewarden/registry: ghcr.io
  kubewarden/repository: kubewarden/policies/volumes-psp
  kubewarden/resources: Pod
  kubewarden/rules: |
    - apiGroups:
      - ''
      apiVersions:
      - v1
      resources:
      - pods
      operations:
      - CREATE
      - UPDATE
  kubewarden/tag: v1.1.4
appVersion: 1.1.4
description: Pod Security Policy that controls usage of volumes
home: https://github.com/kubewarden/volumes-psp-policy
keywords:
- psp
- pod
- volumes
name: volumes-psp
sources:
- ghcr.io/kubewarden/policies/volumes-psp:v1.1.4
version: 1.1.4
