annotations:
  artifacthub.io/repository: kubewarden-policy-library
  catalog.cattle.io/hidden: "true"
  catalog.cattle.io/type: kubewarden-policy
  catalog.cattle.io/ui-component: kubewarden
  kubewarden/displayName: Echo
  kubewarden/mutation: "false"
  kubewarden/registry: ghcr.io
  kubewarden/repository: kubewarden/policies/echo
  kubewarden/resources: '*'
  kubewarden/rules: |
    - apiGroups:
      - '*'
      apiVersions:
      - '*'
      resources:
      - '*'
      operations:
      - CREATE
      - UPDATE
      - DELETE
      - CONNECT
  kubewarden/tag: v0.1.16
appVersion: 0.1.16
description: A policy that echoes back Kubernetes' AdmissionReview - useful for Policy
  Authors
home: https://github.com/kubewarden/policies
keywords:
- developer
name: echo
sources:
- ghcr.io/kubewarden/policies/echo:v0.1.16
version: 0.1.16
