annotations:
  artifacthub.io/repository: kubewarden-policy-library
  catalog.cattle.io/hidden: "true"
  catalog.cattle.io/type: kubewarden-policy
  catalog.cattle.io/ui-component: kubewarden
  kubewarden/displayName: Disallow Service Nodeport
  kubewarden/mutation: "false"
  kubewarden/registry: ghcr.io
  kubewarden/repository: kubewarden/policies/disallow-service-nodeport
  kubewarden/resources: Service
  kubewarden/rules: |
    - apiGroups:
      - ''
      apiVersions:
      - v1
      resources:
      - services
      operations:
      - CREATE
      - UPDATE
  kubewarden/tag: v0.1.11
appVersion: 0.1.11
description: A policy that prevents the creation of Service resources of type `NodePort`
home: https://github.com/kubewarden/policies
keywords:
- service
name: disallow-service-nodeport
sources:
- ghcr.io/kubewarden/policies/disallow-service-nodeport:v0.1.11
version: 0.1.11
