annotations:
  artifacthub.io/repository: kubewarden-policy-library
  catalog.cattle.io/hidden: "true"
  catalog.cattle.io/type: kubewarden-policy
  catalog.cattle.io/ui-component: kubewarden
  kubewarden/displayName: Selinux PSP
  kubewarden/mutation: "true"
  kubewarden/registry: ghcr.io
  kubewarden/repository: kubewarden/policies/selinux-psp
  kubewarden/resources: Pod
  kubewarden/rules: |
    - apiGroups:
      - ''
      apiVersions:
      - v1
      resources:
      - pods
      operations:
      - CREATE
      - UPDATE
  kubewarden/tag: v1.0.7
appVersion: 1.0.7
description: Replacement for the Kubernetes Pod Security Policy that controls the
  usage of SELinux
home: https://github.com/kubewarden/policies
keywords:
- psp
- container
- runtime
- selinux
name: selinux-psp
sources:
- ghcr.io/kubewarden/policies/selinux-psp:v1.0.7
version: 1.0.7
