annotations:
  artifacthub.io/repository: kubewarden-policy-library
  catalog.cattle.io/hidden: "true"
  catalog.cattle.io/type: kubewarden-policy
  catalog.cattle.io/ui-component: kubewarden
  kubewarden/displayName: Safe Annotations
  kubewarden/mutation: "false"
  kubewarden/registry: ghcr.io
  kubewarden/repository: kubewarden/policies/safe-annotations
  kubewarden/resources: '*'
  kubewarden/rules: |
    - apiGroups:
      - '*'
      apiVersions:
      - '*'
      resources:
      - '*'
      operations:
      - CREATE
      - UPDATE
  kubewarden/tag: v1.0.4
appVersion: 1.0.4
description: A policy that validates Kubernetes' resource annotations
home: https://github.com/kubewarden/policies
keywords:
- annotations
name: safe-annotations
sources:
- ghcr.io/kubewarden/policies/safe-annotations:v1.0.4
version: 1.0.4
