annotations:
  artifacthub.io/repository: kubewarden-policy-library
  catalog.cattle.io/hidden: "true"
  catalog.cattle.io/type: kubewarden-policy
  catalog.cattle.io/ui-component: kubewarden
  kubewarden/displayName: Flexvolume Drivers Psp
  kubewarden/mutation: "false"
  kubewarden/registry: ghcr.io
  kubewarden/repository: kubewarden/policies/flexvolume-drivers-psp
  kubewarden/resources: Pod
  kubewarden/rules: |
    - apiGroups:
      - ''
      apiVersions:
      - v1
      resources:
      - pods
      operations:
      - CREATE
      - UPDATE
  kubewarden/tag: v1.0.13
appVersion: 1.0.13
description: Replacement for the Kubernetes Pod Security Policy that controls the
  allowed `flexVolume` drivers
home: https://github.com/kubewarden/policies
keywords:
- psp
- container
- runtime
- flex volume
- flex
name: flexvolume-drivers-psp
sources:
- ghcr.io/kubewarden/policies/flexvolume-drivers-psp:v1.0.13
version: 1.0.13
