annotations:
  artifacthub.io/repository: kubewarden-policy-library
  catalog.cattle.io/hidden: "true"
  catalog.cattle.io/type: kubewarden-policy
  catalog.cattle.io/ui-component: kubewarden
  kubewarden/displayName: Sysctl PSP
  kubewarden/mutation: "false"
  kubewarden/registry: ghcr.io
  kubewarden/repository: kubewarden/policies/sysctl-psp
  kubewarden/resources: Pod
  kubewarden/rules: |
    - apiGroups:
      - ''
      apiVersions:
      - v1
      resources:
      - pods
      operations:
      - CREATE
      - UPDATE
  kubewarden/tag: v1.0.10
appVersion: 1.0.10
description: A Pod Security Policy that controls usage of sysctls in pods
home: https://github.com/kubewarden/policies
keywords:
- sysctl
- psp
- pod
name: sysctl-psp
sources:
- ghcr.io/kubewarden/policies/sysctl-psp:v1.0.10
version: 1.0.10
